### PR TITLE
aosp_build: correct path for backup service overlay

### PR DESCRIPTION
**Pull request by alviteri**
it is defined at defaults.xml since android-5.0.0_r1 tag

https://android.googlesource.com/platform/frameworks/base/+/android-5.0.0_r1/packages/SettingsProvider/res/values/defaults.xml#55

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by Blystad** [comment]
That should, strictly speaking, not matter at all.

All the XML files in res/values/X.xml gets merged together and compiled. At least that's how I understand the system.

Tried printing out the value seen in the Java/C++ layer and checked that it's correct?

**Comment by alviteri** [comment]
I don't how much influent this but I have had this https://github.com/SonyAosp/device_sony_common/blob/android-7.1/overlay/frameworks/base/packages/SettingsProvider/res/values/defaults.xml and never seen the bug explained here https://github.com/opengapps/aosp_build/issues/109

**Comment by alviteri** [comment]
https://github.com/LineageOS/android_vendor_cm/blob/cm-14.1/overlay/common/frameworks/base/packages/SettingsProvider/res/values/defaults.xml

**Comment by Blystad** [comment]
Since this hasn't been updated since February I'm closing it.

**Pull request closed without merging**
