### PR TITLE
build: Add GooglePackageInstaller

### PR DESCRIPTION
**Pull request by alviteri**
Override PackageInstaller from AOSP

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
@Blystad I hope is ok .... tell me .... thanks

**Comment by mfonville** [comment]
You have used the wrong package id. This is the 'pano' one, which is meant for Android TV.

**Comment by alviteri** [comment]
Ok thanks ... is this the correct one ? https://github.com/opengapps/all/tree/master/priv-app/com.google.android.packageinstaller/23/nodpi

**Comment by mfonville** [comment]
Yes, that one is the correct one.

**Comment by Blystad** [comment]
Since it needs to be put in `/system/priv-app` you also need to add `LOCAL_PRIVILEGED_MODULE := true` in the makefile.

**Comment by alviteri** [comment]
fixed

**Comment by Blystad** [comment]
Great. Thanks.

**Comment by alviteri** [comment]
Np I love this project make me happy, have my aosp builds with Gapps xD

**Comment by bkuhls** [comment]
On Oct 10 the api25 version of this package was added:
https://github.com/opengapps/all/commit/29b575738b7b669e5fec071f364fe14889a129d5

Does it still make sense to block this package for Nougat?

Apparently this leads to problems with permissions dialogs:
http://forum.xda-developers.com/showpost.php?p=69143987&postcount=3243

**Comment by sevenrock** [comment]
On Oct 10 the api25 version of this package was added:
opengapps/all@29b5757

Does it still make sense to block this package for Nougat?

Apparently this leads to problems with permissions dialogs:
http://forum.xda-developers.com/showpost.php?p=69143987&postcount=3243

**Pull request merged**
