### PR TITLE
Improve error when we can't find the APK

### PR DESCRIPTION
**Pull request by Blystad**
Related to issue #172 and #168

### CODE REVIEW

**Comment by jamuir** [comment]
looks good to me :-)

merge away.

**Comment by jmarcet** [comment]
I am trying to add gapps to cm_android_x86_64 7.1.2 and the build still fails:

`
jmarcet@himawari:/storage/src/android/x86/cm14$ m -j12 iso_img                                                                           
make: Entering directory '/storage/src/android/x86/cm14'
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=7.1.2
LINEAGE_VERSION=14.1-20180415-UNOFFICIAL-android_x86_64
TARGET_PRODUCT=cm_android_x86_64
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=x86_64
TARGET_ARCH_VARIANT=x86_64
TARGET_CPU_VARIANT=
TARGET_2ND_ARCH=x86
TARGET_2ND_ARCH_VARIANT=x86
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.14.13-20.22-ivyb-x86_64-with-Ubuntu-16.04-xenial
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=NJH47F
OUT_DIR=/storage/src/android/x86/cm14/out
WITH_SU=true
============================================
Running kati to generate build-cm_android_x86_64.ninja...
/storage/src/android/x86/cm14/out/build-cm_android_x86_64.ninja is missing, regenerating...
============================================
PLATFORM_VERSION_CODENAME=REL
PLATFORM_VERSION=7.1.2
LINEAGE_VERSION=14.1-20180415-UNOFFICIAL-android_x86_64
TARGET_PRODUCT=cm_android_x86_64
TARGET_BUILD_VARIANT=userdebug
TARGET_BUILD_TYPE=release
TARGET_BUILD_APPS=
TARGET_ARCH=x86_64
TARGET_ARCH_VARIANT=x86_64
TARGET_CPU_VARIANT=
TARGET_2ND_ARCH=x86
TARGET_2ND_ARCH_VARIANT=x86
TARGET_2ND_CPU_VARIANT=
HOST_ARCH=x86_64
HOST_2ND_ARCH=x86
HOST_OS=linux
HOST_OS_EXTRA=Linux-4.14.13-20.22-ivyb-x86_64-with-Ubuntu-16.04-xenial
HOST_CROSS_OS=windows
HOST_CROSS_ARCH=x86
HOST_CROSS_2ND_ARCH=x86_64
HOST_BUILD_TYPE=release
BUILD_ID=NJH47F
OUT_DIR=/storage/src/android/x86/cm14/out
WITH_SU=true
============================================
build/core/binary.mk:1253: external/mesa/src/mesa/Android.libmesa_dricore.mk: libmesa_dricore: Unused source files: x86-64/x86-64.h
build/core/binary.mk:1253: external/mesa/src/mesa/Android.libmesa_dricore.mk: libmesa_dricore: Unused source files: x86/assyntax.h x86/clip_args.h x86/norm_args.h x86/xform_args.h x86/common_x86_asm.h x86/common_x86_features.h x86/x86_xform.h x86/mmx.h x86/mmx_blendtmp.h x86/3dnow.h x86/sse.h
build/core/binary.mk:1253: external/mesa/src/mesa/Android.libmesa_st_mesa.mk: libmesa_st_mesa: Unused source files: x86-64/x86-64.h
build/core/binary.mk:1253: external/mesa/src/mesa/Android.libmesa_st_mesa.mk: libmesa_st_mesa: Unused source files: x86/assyntax.h x86/clip_args.h x86/norm_args.h x86/xform_args.h x86/common_x86_asm.h x86/common_x86_features.h x86/x86_xform.h x86/mmx.h x86/mmx_blendtmp.h x86/3dnow.h x86/sse.h
find: ‘/storage/src/android/x86/cm14/out/target/common/obj/SHARED_LIBRARIES/libwifi-hal-mock_intermediates’: No such file or directory
lunzip: Output file 'vendor/opengapps/sources/x86_64/app/com.android.chrome/24/nodpi/332510962.apk' already exists, skipping.
vendor/opengapps/build/core/prebuilt_apk.mk:50: *** Unable to find APK for GoogleCamera.
build/core/ninja.mk:166: recipe for target '/storage/src/android/x86/cm14/out/build-cm_android_x86_64.ninja' failed
make: *** [/storage/src/android/x86/cm14/out/build-cm_android_x86_64.ninja] Error 1
make: Leaving directory '/storage/src/android/x86/cm14'

#### make failed to build some targets (01:20 (mm:ss)) ####
`

**Comment by Blystad** [comment]
GoogleCamera doesn't exist for x86. So you need to exclude it. See
GAPPS_EXCLUDE_PACKAGES

**Comment by jmarcet** [comment]
I already tried that, but it still bails out:

```
diff --git a/device.mk b/device.mk
index 1416ecd..eaa16da 100644
--- a/device.mk
+++ b/device.mk
@@ -14,6 +14,16 @@
 # limitations under the License.
 #
 
+#OpenGAPPS
+GAPPS_VARIANT := pico
+
+GAPPS_FORCE_BROWSER_OVERRIDES := true
+
+GAPPS_EXCLUDED_PACKAGES := FaceLock \
+    AndroidPlatformServices \
+    PrebuiltGmsCoreInstantApps \
+    GoogleCamera
+
 PRODUCT_DIR := $(dir $(lastword $(filter-out device/common/%,$(filter device/%,$(ALL_PRODUCTS)))))
 
 PRODUCT_PROPERTY_OVERRIDES := \
@@ -115,6 +125,8 @@ $(call inherit-product,frameworks/native/build/tablet-10in-xhdpi-2048-dalvik-hea
 # Get GMS
 $(call inherit-product-if-exists,vendor/google/products/gms.mk)
 
+$(call inherit-product, vendor/opengapps/build/opengapps-packages.mk)
+
 # Get native bridge settings
 $(call inherit-product-if-exists,$(LOCAL_PATH)/nativebridge/nativebridge.mk)
 
```

**Comment by Blystad** [comment]
Of course...ugh...it happens in two passes. First pass of Androids build
system collects makefiles. The second decides what to build and not build.

For now just remove the GoogleCamera android makefile, then I'll give some
thought on how to solve this better.

**Comment by jmarcet** [comment]
All right, I've had to remove four makefiles to get the build for x86 going:

```
On branch cm14-yoga
Your branch is up to date with 'opengapps/master'.

Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        deleted:    modules/GoogleCamera/Android.mk
        deleted:    modules/PrebuiltGmsCoreInstantApps/Android.mk
        deleted:    modules/Street/Android.mk
        deleted:    modules/Tycho/Android.mk

```

**Comment by jamuir** [comment]
@Blystad:  I've tested the following change in `prebuilt_apk.mk` and it works:

```make
ifndef LOCAL_SRC_FILES
ifeq ( ,$(filter $(LOCAL_MODULE),$(GAPPS_EXCLUDED_PACKAGES)))
   $(error Unable to find APK for $(LOCAL_MODULE))
endif
endif
```

**Comment by Blystad** [comment]
Nice. Add a $(strip, and check for empty string instead of a space, then I
think we'll just go with that. Will you make a PR?

**Comment by jamuir** [comment]
Yes, I'll open a PR.

**Comment by jamuir** [comment]
Here it is:  https://github.com/opengapps/aosp_build/pull/178

**Pull request merged**
