### PR TITLE
Pixel sysconfigs

### PR DESCRIPTION
**Pull request by Rashed97**
Corresponding sources/all PR: https://github.com/opengapps/all/pull/32 (IDK if you can see it or not, GitHub's being slow today...)

### CODE REVIEW

**Comment by Rashed97** [comment]
@alviteri IDK if you got this a few days ago when GitHub was being fritzy. Also are there any plans to merge experimental2017 and experimental2018 in sources/all?

**Comment by alviteri** [comment]
Hi @Rashed97 thanks for the contributions but unfortunately I can't merge in all only here .. ask @NicholasBuse for it

**Comment by NicholasBuse** [comment]
Merged "all". Thanks!

**Comment by Rashed97** [comment]
Thanks guys!

**Pull request merged**
