### PR TITLE
package name of SetupWizard is corrected

### PR DESCRIPTION
**Pull request by moku**
Due to incorrect package name of SetupWizard module, compile fails.
Package name changed from 'com.google.android.setupwizard.default' to 'com.google.android.setupwizard'

### CODE REVIEW

**Comment by mfonville** [comment]
@moku on 5.0+ the setupwizard is on purpose renamed with .default in the Open GApps sources repos, to differentiate the 'tablet' and the 'default' setupwizard (they are identified as such by decompiling the APK and looking at a value)

**Comment by Blystad** [comment]
See issue #101 

It needs to be `.default` on 5.0+

You can do something like:

```
ifneq ($(filter $(call get-allowed-api-levels),21),)
# kitkat here
LOCAL_PACKAGE_NAME := com.google.android.setupwizard
else
# original code here, that handles LP and newer.
endif
```

also delete the .swp file.

**Comment by moku** [comment]
Thanks for review.
I'll apply the comments and commit.

**Comment by Blystad** [comment]
I think the .tablet version doesn't exist for KitKat, so you need to overwrite that as well for KitKat.

Do something like:

```
ifeq ($(filter $(call get-allowed-api-levels),21),)
    # Kitkat
    LOCAL_PACKAGE_NAME := com.google.android.setupwizard
else
    ifneq ($(filter $(PRODUCT_CHARACTERISTICS),tablet),)
        LOCAL_PACKAGE_NAME := com.google.android.setupwizard.tablet
    else
        LOCAL_PACKAGE_NAME := com.google.android.setupwizard.default
    endif
endif
```

Also, please squash your commits. :)

**Pull request closed without merging**
