### PR TITLE
Fix the link to git-lfs README

### PR DESCRIPTION
**Pull request by wanderlusttt**

### CODE REVIEW

**Review by MartinX3 — CHANGES_REQUESTED** [review]
Useless change. Fixes nothing. Revert it.

**Comment by wanderlusttt** [comment]
> Useless change. Fixes nothing. Revert it.

Yes, it fixes nothing. But would match with the actual branch.

**Comment by MarijnS95** [comment]
The branch rename redirect works, so either is fine.

The PR/commit title is completely not representing what is being changed here though, making this PR unmergeable.

**Comment by wanderlusttt** [comment]
> The branch rename redirect works, so either is fine.
> 
> The PR/commit title is completely not representing what is being changed here though, making this PR unmergeable.

It could be edited by the maintainers. Still I have edited it now. 
Yeah, I agree it branch redirect work, but I thought to contribute by correcting it. Thanks.

**Pull request closed without merging**
