### PR TITLE
9.0

### PR DESCRIPTION
**Pull request by alviteri**

### CODE REVIEW

**Comment by alviteri** [comment]
@jamuir @Blystad please review this ... thanks

**Comment by jamuir** [comment]
Looks good to me.

I'll be interested to see if there is anything different with my oreo builds now that GmsGoreSetupPrebuilt is included.

I say merge when you are ready.

**Comment by alviteri** [comment]
@jamuir https://github.com/opengapps/arm64/pull/5/commits/3d2055fb43bfc541fd1be061a4a59c6bd6a950c7 this one ... the libs are not be copied to system/lib64 | vendor/lib64

**Comment by alviteri** [comment]
infact markupgoogle crashes due to missing lib libsketchology_native.so

**Pull request merged**
