### PR TITLE
new package: com.google.earth

### PR DESCRIPTION
**Pull request by sevenrock**

### CODE REVIEW

**Comment by Blystad** [comment]
Thanks for your contribution. Seems this package is included by default in the `super` package level:

https://github.com/opengapps/opengapps/wiki/Package-Comparison

Could you update your PR to also do this? Thanks :)

**Comment by sevenrock** [comment]
Is it enough to add this?

GAPPS_LOCAL_OVERRIDES_MIN_VARIANT := super

**Comment by Blystad** [comment]
Just add it after this line:

https://github.com/opengapps/aosp_build/blob/master/opengapps-packages.mk#L92

(Remember to put a backslash ( `\` ) on the item above) :)

**Comment by sevenrock** [comment]
Done

**Comment by Blystad** [comment]
perfect, thanks :)

**Pull request merged**
