### PR TITLE
Allow override AOSP Browser

### PR DESCRIPTION
**Pull request by alviteri**
also include needed overlay for frameworks

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
@Blystad this still will let you change default browser in settings-apps

**Comment by Blystad** [comment]
Seems I was a bit too fast in merging this in:

```
vendor/google/build/overlay/browser/frameworks/base/core/res/res/values/config.xml:29: error: Resource at default_browser appears in overlay but not in the base package; use <add-resource> to add.
```

**Comment by Blystad** [comment]
I guess the overlay should only be included on Marshmallow and above. On Lollipop the key doesn't exist.

**Comment by alviteri** [comment]
only .... that ?.... sorry I didn't test in L

**Comment by Blystad** [comment]
I pushed 1acbc75c613ba6ceb19f0b383fe7150bcf885123 to fix it :)

**Comment by alviteri** [comment]
thanks .... and sorry for not check L

**Pull request merged**
