### PR TITLE
aosp_build: build GmsCoreInstantApps

### PR DESCRIPTION
**Pull request by alviteri**
Google Play Services for InstantApps (allow nougat for now)

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by alviteri** [comment]
@mfonville I am not sure if this is allowed by M or before .....

**Comment by alviteri** [comment]
@Blystad any news for this ?

**Comment by Blystad** [comment]
Can you move the stuff in packages.mk after API level 23 check, (so we have
23, then 24, makes it easier to read).

Then I'll merge it.

On 13 Aug 2017 11:09, "David Viteri" <notifications@github.com> wrote:

@Blystad <https://github.com/blystad> any news for this ?

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/opengapps/aosp_build/pull/143#issuecomment-322030733>,
or mute the thread

**Comment by alviteri** [comment]
now ?

**Comment by Blystad** [comment]
I was thinking:

```diff
 ifneq ($(filter $(call get-allowed-api-levels),23),)
 GAPPS_PRODUCT_PACKAGES += \
     GoogleTTS \
     GooglePackageInstaller
 endif
+ifneq ($(filter $(call get-allowed-api-levels),24),)
+GAPPS_PRODUCT_PACKAGES += PrebuiltGmsCoreInstantApps
+endif
+
```

Do we know if the PrebuiltGmsCoreInstantApps work on Marshmallow?

**Comment by alviteri** [comment]
ok but my first patch was API 24 .... ok let me update
thanks

**Comment by alviteri** [comment]
updated

**Pull request merged**
