### PR TITLE
new package: com.google.android.webview

### PR DESCRIPTION
**Pull request by Blystad**
Added webview based on PR #1 from @sevenrock and set it to the correct default package, with a AOSP framework resource override.

### CODE REVIEW

**Comment by mfonville** [comment]
:+1:

**Comment by mstfkaratas** [comment]
Does "LOCAL_MODULE_OVERRIDES := webview" work? because webview folder and corresponding lib are still in system/app and system/lib after successfull build of cm12.1.

**Comment by Blystad** [comment]
Blergh, I misspelled it...it's actually

LOCAL_OVERRIDES_PACKAGES

I also need to move the webview package up to stock. I considered making it
a core package but to ensure the opengapps matrix matches we should put it
under stock.

**Comment by Blystad** [comment]
Fixed the last issues now.

**Pull request merged**
