### PR TITLE
aosp: use better code style

### PR DESCRIPTION
**Pull request by alviteri**
Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by jamuir** [comment]
thanks for cleaning up the makefile :-)

those long multi-line variable assignments are much easier to read now.

**Comment by Blystad** [comment]
I've moved the GAPPS_PRODUCT_PACKAGES filter to the end of the file in commit https://github.com/opengapps/aosp_build/commit/cb3629afdb53bca92ae5ba1b9f75f6788b7a0c0d

so it should be fine now.

**Comment by jamuir** [comment]
@alviteri , @Blystad:  I should have given more explanation about why the filter command wasn't placed at the end of the file.

The problem is that the modules considered below line 117 also update DEVICE_PACKAGE_OVERLAYS.

Consider someone who is using `stock` but doesn't want `Chrome` installed.  Then they would add `Chrome` to GAPPS_EXCLUDED_PACKAGES.

In that case, we should not update `DEVICE_PACKAGE_OVERLAYS` for the Chrome overlay, but with the filter command at the end of the end, that is what will happen.

joint filtering of DEVICE_PACKAGE_OVERLAYS and PRODUCT_PACKAGES seemed complicated to me, so I avoided it by not placing `PRODUCT_PACKAGES += $(filter-out $(GAPPS_EXCLUDED_PACKAGES),$(GAPPS_PRODUCT_PACKAGES))` at the end of the file.  I should made this more obvious by adding a comment above the `filter-out` command.

**Comment by Blystad** [comment]
Right....good point. I didn't consider that. Let's get that fixed. If
you're up for fixing it I will approve the PR tonight. Otherwise I'll fix
it myself later tonight or tomorrow :)

**Pull request merged**
