### PR TITLE
make round icons opt-in

### PR DESCRIPTION
**Pull request by alviteri**
do this for android oreo launcher which can use adaptive icons

Signed-off-by: David Viteri <davidteri91@gmail.com>

### CODE REVIEW

**Comment by Blystad** [comment]
Why should it be opt in? Isn't round icons the new cool thing in Oreo?

**Comment by alviteri** [comment]
arne pixel launcher in oreo can use adaptive icons

**Comment by alviteri** [comment]
also round icons was introduced on nougat 25 api level

**Comment by alviteri** [comment]
Look the adaptive icons for file manager or SIM toolkit etc etc
screenshot_20171002-020042

**Comment by alviteri** [comment]
since I think this will not be merged I am closing

**Pull request closed without merging**
