### PR TITLE
Use AOSP local_manifests feature

### PR DESCRIPTION
**Pull request by fonic**
Instead of altering existing manifests, additional 'overlay' manifests can be but in `.repo/local_manifests`. The repo tool automatically includes files in this folder.

[http://forum.xda-developers.com/showthread.php?t=2329228](http://forum.xda-developers.com/showthread.php?t=2329228)

### CODE REVIEW

**Comment by Blystad** [comment]
Hey, 

Thanks for the contribution.

How will this be if a team is working together on a ROM? Does each team member need to do this, or is it checked into git?

**Comment by fonic** [comment]
In a project I was involved we put the overlay manifest on GitHub and initialized the repo like this (nice and easy):

```
# Initialize repository
repo init -u https://android.googlesource.com/platform/manifest -b master

# Add local manifest
mkdir -p .repo/local_manifests
curl https://<github>/overlay.xml > .repo/local_manifests/overlay.xml

# Sync repo
repo sync
```

**Comment by Blystad** [comment]
I think I'm a bigger fan of both alternatives being presented to the user. 

Maybe your local_manifest solution first, and then the custom manifest.xml solution afterwards. Thoughts?

**Comment by fonic** [comment]
I think that's a great idea, then the user can decide which solution fits his needs.

**Comment by Blystad** [comment]
Closing this since it hasn't been updated. Feel free to re-open in the future with the necessary changes :)

**Pull request closed without merging**
